### ISSUE TITLE
Support for TIFF file format

### ISSUE THREAD

**Issue by jigneshchudasama** [Mawi137/ngx-image-cropper#107]
Does your plugin provide support for the 'TIFF' image type?

**Comment by Mawi137** [comment]
Hi, since it uses a HTML canvas under the hood and that doesn't support TIFF, the image cropper won't either. It seems TIFF can be loaded into an image cropper, so I could allow the image-cropper to accept that. The output depends on browser support for it, but TIFF is not one of them, png is the only one supported by all browsers.

**Comment by jigneshchudasama** [comment]
Yes, please allow TIFF format as an input format

**Comment by Mawi137** [comment]
TIFF should now be allowed, version 1.2.3
