### ISSUE TITLE
base64 image url is black on mobile

### ISSUE THREAD

**Issue by milo157** [Mawi137/ngx-image-cropper#156]
I am cropping images and then using the base64 url from the ImageCroppedEvent. On desktop this seems to work perfectly however on mobile sometimes the image renders black. I tried it on both Safari and Chrome on my iPhone and it occurs on both.

I haven't been able to pinpoint exactly in what situations it happens and why, I have just seen it has to do with the base64 url that is generated.

**Comment by Mawi137** [comment]
I don't have an iPhone myself so I'm unable to try it myself. Without any error there's not much I can do..

**Comment by drakedeatonuk** [comment]
@milo157 did you ever find the cause of this? Still experiencing this issue on web safari

**Comment by fox-alvarez** [comment]
To reproduce the issue on mobile devices, it seems to be related to selecting extremely large images from the gallery.

In my experience using an iPhone 15, I took a standard photo with a resolution of 24 MP (4284 x 5712 pixels), and consistently encountered this error. However, when I tried with smaller images, such as those around 12 MP, the issue did not occur.

This leads me to believe that the problem is tied to the handling of high-resolution images. A potential solution could be to implement a configuration that reduces the image size before processing it with ngx-image-cropper. Does anyone have suggestions or experience with configuring ngx-image-cropper or the surrounding code to handle large images more effectively on mobile devices?
