### ISSUE TITLE
Doesn't work in Safari browsers, or in IOS in general even on chrome browser.

### ISSUE THREAD

**Issue by HELkashef90** [Mawi137/ngx-image-cropper#195]

**Comment by picciama** [comment]
@HELkashef90 could you provide a more detailed description of the problem, like how it actually behaves? 
Does it freeze completely?
Is it not possible to move the borders by swiping with the finger?
Or does this only work sometimes and does it take a long time until it is responsive again after a resize event?

@Mawi137
My clients using my webview app on iOS told me about these issues too, I could reproduce them with various image sizes and formats but it seems to occur randomly. Tomorrow, I will try to give more information when debugging with xcode.

**Comment by picciama** [comment]
Sorry, cannot find out the reason. 
My investigations showed that the problem is related to using images that were taken with the phone itself. Downloaded images are working ok. Maybe related to issues with EXIF data, as suggested by many other issues in related image croppers. The problem can be seen on android too, however, not as severe. With very large images, the reaction time is perceivably slower after resizing.

**Comment by hasnentai** [comment]
@Sruthi-Dintakurty I am facing the same issue.
Normally the image taken with the phone camera is more than 1 Mb and its completely freeze when we load the image which is more than  1 Mb

**Comment by hasnentai** [comment]
@Mawi137 @Sruthi-Dintakurty @picciama @HELkashef90 

So after a long day working on the image cropper I figured out what is the problem.First thing first.
The cropper works perfectly fine on the PC browser and that's the great news .
**>Now here is the problem which we are facing on IOS.(May on all the Old phones)**
When we click a picture on IOS with the back camera, the result of the picture is almost more then 2 Mb or 3 Mb. So now what happens here is when we load the image form the gallery the image cropper convert the image to png and produce the Base 64 which will result in a huge string.My findings and observation says that when we upload the image of 2Mb or More than that the Base64 string results to be more then 12 Mb so indirectly the image is being converted to the larger size and mobile browser is not able to handle that big string and It will leads to lag the cropper or totally freez or may be the browser page reload .

What I did to get ride of this is ,I am getting the result in jpeg instead of PNG and manually setting the image quality.
If interested please let me know will share the code here 

Thanks

**Comment by Mawi137** [comment]
Hi @hasnentai 
That's interesting. Which filetype is used by iOS?

The problem with jpeg is that not all browsers support it when you want to get the base64 string from the canvas. According to the standards, png must always be supported, the rest is optional.

**Comment by hasnentai** [comment]
Thanks for the response @Mawi137 
**Normally IOS images are given as jpg image format.**
Well please take a look on the PNG why the strings are getting bigger size and give a solution to this because its more important to work on mobile phone  and that is the reason we are using angular.

**Comment by Mawi137** [comment]
Using jpeg will result in loss of quality, but it's indeed more important that it works. Maybe I can add something that only works on mobile and starting from a certain filesize/dimension.

**Comment by hasnentai** [comment]
@Mawi137 
some time its worst in result Yesterday i was testing image which was around 15 Mb and its base64 was 149 Mb well this can be managed by the computer browser but not by the mobile browser

**Comment by REPTILEHAUS** [comment]
+1 for this, Im having a similar issue I think with this plugin https://github.com/web-dave/ngx-img-cropper/issues/82 will switch to yours if this gets solved :) 

Since upgrading to capacitor Im noticing base64 strings go on forever so this is potentially whats causing my problem too

**Comment by abizit** [comment]
Any updates on this?? I am facing similar issue. Andriod seems to be fine though but on IOS if i move the cropper for multiple times the whole thing freezes.

**Comment by hverma** [comment]
+1. Experience on IOS is really bad.  The image either doesn't or the whole thing freezes when trying to move the cropper.
Any ideas when fix will be released?

**Comment by gdinn** [comment]
I found the solution! Probably you don't set the "autoCrop" input (which by default is true) and, in my case, I don't really need it. What it does is to crop the image and do all the operations with it every time that you change the cropping area, which I think that dry all safari resources.

Try to declare like this:

`    <image-cropper
        [imageBase64]="imageBase64"
        [maintainAspectRatio]="true"
        [aspectRatio]="1"
        [resizeToWidth]="800"
        [cropperMinWidth]="800"
        [onlyScaleDown]="true"
        [autoCrop]="false"
        format="png"        
    ></image-cropper>`

And to crop the image when you actually need it:
`  
croppedImage
@ViewChild(ImageCropperComponent) imageCropper: ImageCropperComponent;
async obtainCroppedImage(){
        let image = await this.imageCropper.crop()
        this.croppedImage = image.base64
}
`

**Comment by hverma** [comment]
@gdinn  for me a image over 5mb doesn't even load on an iOS device.

**Comment by gdinn** [comment]
@hverma where did you get images this big? In my application I use images direct from the camera (base64 output from the plugin) with this exact code and it works well.

**Comment by hverma** [comment]
@gdinn Images directly from camera is fine. Images from Photo Library vary in size. Sometimes images around 3.5mb are also not loading for me on iOS.

**Comment by gdinn** [comment]
@hverma You are right. I think in this case we have to control this with the loading error event and advise the user to choose a small image or take one with the camera.

**Comment by hverma** [comment]
@gdinn thx for the suggestion. However, it will be poor user experience.

FYI, I tried it with ng2-img-cropper, images large seems to load fine.

**Comment by Sagarkhenat** [comment]
@hasnentai @Mawi137  could you possibly share your code here for image-cropper solution on iOS.The cropper works good on android and browser, but I am facing issues while working the same on iOS

**Comment by Serginho** [comment]
I'm not sure if it's actully the size, I have 187kb images that it doesn't work. Any updates on this?

**Comment by a777med** [comment]
Any updates? I can't get it working on Safari, either.

**Comment by skyofdust** [comment]
The problem is still actual on all version of ios in Safari and Chrome and it mainly affects bigger images, both taken with camera and loaded from photo library. It happens also for some images below 1MB.

It seems that problem starts once the image is converted to data url, regardless of the size, even before it is passed to the cropper.
Once the problem manifests, image is visible in the cropper component and cropped area covers full image. Image can be exported successfully. If I try to crop few images in a row, it could happen that first image is bugged, but the second, smaller is working.
I spotted one more thing - once the problem occurs, cropper is still usable, but I have to use two fingers to move the crop boundaries - if next image is not bugged, cropper works with single finger.

I tried to downsize the image before it is passed to the cropper and it made no difference.

I'm having problem with this for some time and I'm really close to switch to some alternative library.

**Comment by Mawi137** [comment]
Have you tried using the blob output type instead of base64 ? Like that it doesn't convert the images to base64 strings anymore which should result in better performance.

**Comment by skyofdust** [comment]
Thank you for your suggestion, I refactored the code not to use base64 and to use blob and objectUrl instead. Result is that images are loading faster, but the problem persists. What I find very interesting is that if the image has aspect ratio such that width is bigger than height, cropper is not working as expected (still works with two fingers touch), but if such image is rotated so that height is bigger than width, cropper is working fine. Also if the original image's hight is bigger than width, cropper is working fine.
