### ISSUE TITLE
Can we fix max width and height like [cropperMinWidth] and [cropperMinHeight]

### ISSUE THREAD

**Issue by SanjanaKhater** [Mawi137/ngx-image-cropper#219]

**Comment by Mawi137** [comment]
Sure, feel free to create a PR!

**Comment by m-kashif** [comment]
any progress on this?

**Comment by priyarajagopal1126** [comment]
any idea about this?

**Comment by KyubiBoy** [comment]
Any news about this? I really need it for a project :)

**Comment by hanyska** [comment]
+1

**Comment by ekzGuille** [comment]
I like this cropper but I think it is missing a funcionality. Set image-cropper max width/height.
Because if you load a vertical, horizontal or square image, depending on the image resolution it will take as much space as it needs. It would be great to establish a max height (or width).
I will try to work on this.

Here are some examples: (Below the image should be 2 buttons but images are pushing them down which is what I want to fix)

* Vertical image without styles
![](https://i.imgur.com/z5t2Dn6.png)

* Vertical image with styles (**deformed image**)
![](https://i.imgur.com/egAh4B8.png)

* Squared image
![](https://i.imgur.com/rAJAgM8.png)

* Horizontal image (**seems to be ok but no, it's still pushing down the buttons**) 
![](https://i.imgur.com/sC3Cs3F.png)

**Comment by ekzGuille** [comment]
It is something I will have to deal in my app. 
I need to change css style in
```css
 image-cropper img {
    object-fit: cover
    ...
}
```

**Comment by AmoghHegde** [comment]
I have raised a PR to implement this feature : https://github.com/Mawi137/ngx-image-cropper/pull/366
Please feel free to review, provide valuable suggestions for the same.

**Comment by BruneXX** [comment]
Will this be merged soon? I think we'll good to have that improvement sooner than later.

**Comment by experionathira** [comment]
any update on this?

**Comment by Mawi137** [comment]
Available since version `3.3.0`.
