### ISSUE TITLE
Incorrect behaviour when cropping using center handles

### ISSUE THREAD

**Issue by hfournier** [Mawi137/ngx-image-cropper#229]
When cropping using the bottom-center handle, I get the same behaviour as if I were using the bottom-right corner handle. That is, the bottom and right move, when I would expect the bottom and both sides to move. All center handles exhibit this incorrect behaviour.

Using 1/1 aspect ratio.
```
          [resizeToHeight]="250"
          [resizeToWidth]="250"
```

**Comment by Mawi137** [comment]
Hi yes this is intentional. Achieving what you want is a lot harder because I think if you make it 1px wider, it will be half a pixel on the left and half a pixel on the right. But the browser will round that up or down, and you’ll get a jumpy cropper. Plus you’ll have to check both sides if the cropper goes out of bounds which will require quite some checks to be done.
Feel free to give it a go. A PR is always welcome :)

**Comment by hfournier** [comment]
It might be worth looking at CropperJS, because it handles it properly and seems pretty smooth.
