### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by wolfbomb** [Mawi137/ngx-image-cropper#283]
I am trying to use imageulr but i got this CORS issue. Not sure if i am doing it right but i tried to add the crossOrigin on the img tag but it didn't help. How can i enable CORS using this cropper?

This is use the the cropper:
![image](https://user-images.githubusercontent.com/4049788/75989361-1a252e00-5f2e-11ea-9aea-15025d8a9b47.png)

This is the issue i got. I am using https on a web api asp.net core. Take note using the url alone and pasting it on the browser works fine but not with cropper.
![image](https://user-images.githubusercontent.com/4049788/75989552-6d977c00-5f2e-11ea-9cd4-42e5c4e02f5e.png)

**Comment by tiagomotasantos** [comment]
If you have access to the server that's hosting the image you can set 'Access-Control-Allow-Origin' HTTP header to the response to solve that. If you are only developing the frontend and have no control of the server you can use a CORS proxy (e.g. https://cors-anywhere.herokuapp.com). 
I recommend that you read this article to understand more about the basics of CORS: https://medium.com/@baphemot/understanding-cors-18ad6b478e2b.

**Comment by Mawi137** [comment]
Maybe instead of using the Angular http client, the image url can be loaded like this in the cropper itself @tiagomotasantos 

https://stackoverflow.com/questions/49503171/the-image-tag-with-crossorigin-anonymous-cant-load-success-from-s3

**Comment by tiagomotasantos** [comment]
I didn't know about the "crossOrigin" attribute but I did some research and some tests in the demo project and this attribute only let's you configure the credentials flag for CORS requests, when set to "anonymous" the credentials property is set to "same-origin", which means user credentials (cookies, basic http auth, etc..) will be sent only if the request is on the same origin. But that still leaves it to the server to allow CORS requests or not. The problem on that question was actually cache, and the accepted answer solved it with cache busting. Still I tried that in the demo project and it doesn't work.

I tried to load the URL directly in the img tag but I had to use `bypassSecurityTrustUrl` which leaves the lib with a XSS vulnerability (making it not a valid option to go with) but the image does show. The problem is you need to get access to the actual image content, to do that I tried to draw the image in the canvas and used the `toDataURL` method to get the content, but that doesn't work because the browser marked the canvas as tainted. To solve that I used the "crossOrigin" attribute on the image to force the server to return the CORS headers, and that goes back to the original point leaving it to the server to allow or not.

To sum up, the only options are to properly implement the CORS headers in the server (which makes sense since is the server that should decide to allow or not to access those resources) or to use a proxy (which is actually really simple to use and works well).

**Comment by Mawi137** [comment]
Well generally you setup your server so the browser doesn't block your own web applications from accessing its resources. That means if you want to use any image from the internet and load it in the image cropper, you must implement a proxy in your own server that simply forwards the image, but has the correct cors header. Even malicious images will no longer be blocked.

Anyway, using the `HttpClient` or `new Image` has the same effect on CORS, but the second one doesn't require the `HttpClientModule`, so it might be better to use that approach?

**Comment by tiagomotasantos** [comment]
Exactly that!

You are right, I'll refactor it to remove the depencency of HttpClientModule and open a PR with that approach!

**Comment by wolfbomb** [comment]
Appreciate all the replies. My issue was gone after reloading my VS Code and re-start my project. All is working fine now using the same code posted above.
