### ISSUE TITLE
Some smaller images about 2MB are converted to 23.5MB png, causing performance issue.

### ISSUE THREAD

**Issue by GaneshVellankiTR** [Mawi137/ngx-image-cropper#317]
Hi,

I am trying to open cropper in modal & when I pass image file directly to input binding its taking time to show crop. To prevent this, I have fetched base64 image data & passed it, still seems to have same behavior. Can you help me how we can improve load times, assuming I already have a source image in base64 ?

**Comment by GaneshVellankiTR** [comment]
![Pleiades_large](https://user-images.githubusercontent.com/54101183/79835586-8e2b7080-83cc-11ea-89b2-d9c3e63bc8f2.jpg)

This is the image I am using.

**Comment by ioaNikas** [comment]
Hello,

You can use a workaround by definingyourself the format of the image after being processed by the cropper with `format` attribute :

```
<image-cropper format="jpg"></image-cropper>
```

However, the extension of your file won't change but the format will.

**Comment by Mawi137** [comment]
Internally each image you upload will be transformed into a new base64 to handle exif rotation (a base64 can also have an exif rotation) and canvas rotation. That's why it needs some time to load. An optimisation I can do is to skip that if there is no rotation or flip horizontal needed. However, once you rotate the canvas, it will still be transformed into a png. Using jpeg internally might improve the performance or at least reduce the size, but it isn't supported by all browsers.

What file type is your base64 @GaneshVellankiTR?

**Comment by Mawi137** [comment]
You can test it out with version 3.1.7. That will no longer transform the image again if a rotation is not needed.

**Comment by GaneshVellankiTR** [comment]
@Mawi137, thank you. I will test it with 3.1.7 & let you know, the format of the image is not restricted to jpg & can be all image formats.

**Comment by GaneshVellankiTR** [comment]
@Mawi137 Thank you for making the change. It is now not trying to generate huge size image in the background.

**Comment by GaneshVellankiTR** [comment]
I have one more question @Mawi137 , do you do anything extra when generating base 64 image output for format="jpeg" because when I opt for jpeg, the base 64 output seems not a valid one for C# backend. I have personally checked encoding seems fine But there is a difference between base64 outputs for format="jpeg" & format="png". I know this is not part of the issue but please educate me. Thank you.

**Comment by GaneshVellankiTR** [comment]
Thank you @Mawi137 & @ioaNikas . Closing the issue.
