### ISSUE TITLE
Cors issue - Not able to load local image resource Ionic V4 

### ISSUE THREAD

**Issue by prteekagni** [Mawi137/ngx-image-cropper#318]
This is the image url http://localhost/_app_file_/storage/emulated/0/Pictures/IMG_20200422_175945.jpg. I works with image tag but not works with image cropper.
Access to image at `'http://localhost/_app_file_/storage/emulated/0/Pictures/IMG_20200422_175945.jpg' from origin 'http://localhost:8100' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by Mawi137** [comment]
Hi there,
Yes that is the problem with loading images using an URL. The server hosting the image should have the correct CORS header set, else it will give you that error. So you can either set the 'Access-Control-Allow-Origin' header for that localhost server you have. Another option is to implement a small proxy service that forwards the call to that url, but adds the header when returning to your app. 

This has nothing to do with the image cropper. It's because of browser security and it's up to you to make sure the url called in the image cropper has the correct `Access-Control-Allow-Origin` header set.

**Comment by prteekagni** [comment]
> t
Thanks mawi137, this is an URL for my image that I got using camera plugin, 
 

>  const options: CameraOptions = {
>       quality: 100,
>       destinationType: this.camera.DestinationType.FILE_URI,
>       encodingType: this.camera.EncodingType.JPEG,
>       mediaType: this.camera.MediaType.PICTURE,
>       saveToPhotoAlbum: true,
>       sourceType: this.camera.PictureSourceType.CAMERA,
>     };
> 
>     this.camera.getPicture(options).then((imageData) => {
>       this.imgUrl = (<any>window).Ionic.WebView.convertFileSrc(imageData);
>       this.readimage();
>     });

I have also converted the same to base64 still getting unsafe out there. Is there any other configuration that can resolve it. Because it is getting loaded in the image tag.

**Comment by Mawi137** [comment]
Not that I know of. So either the image must have the same url as your app or you need the CORS header set. Those are the only 2 solutions I know that work.

**Comment by prteekagni** [comment]
> This is the image url http://localhost/_app_file_/storage/emulated/0/Pictures/IMG_20200422_175945.jpg. I works with image tag but not works with image cropper.
> Access to image at `'http://localhost/_app_file_/storage/emulated/0/Pictures/IMG_20200422_175945.jpg' from origin 'http://localhost:8100' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

thanks for the quick reply
