### ISSUE TITLE
How to get cropped image using cropper/image position

### ISSUE THREAD

**Issue by ColinBrilliantLabs** [Mawi137/ngx-image-cropper#362]
So I have a cropper where someone can upload an image for a project, however, they can edit the project, so I also would like them to be able to edit the image. I was hoping I could store the original image, as well as the cropper/image position. This way if they returned to the editor, they could select a new area to crop if they made a mistake. The issue I'm having is I can't seem to figure out how to display the image afterwards, and crop it using the cropper/image position.

**Comment by MarioMH8** [comment]
> So I have a cropper where someone can upload an image for a project, however, they can edit the project, so I also would like them to be able to edit the image. I was hoping I could store the original image, as well as the cropper/image position. This way if they returned to the editor, they could select a new area to crop if they made a mistake. The issue I'm having is I can't seem to figure out how to display the image afterwards, and crop it using the cropper/image position.

I've the same problem!

**Comment by Mawi137** [comment]
There is currently no out of the box solution. You get the cropper position relative to the full image size after cropping so that you can save. However, you can only give an initial cropper position which is relative to the displayed image and not the full image size. So you'd either have to calculate postion on the full image to the displayed image and pass that or fork this repo, add in that feature and open a PR.
