### ISSUE TITLE
 not compatible with Angular Ivy

### ISSUE THREAD

**Issue by Arashatami** [Mawi137/ngx-image-cropper#379]
@angular/compiler :  ^10.1.6
@angular/core :  ^10.1.6

This likely means that the library (ngx-image-cropper/lib/image-cropper.module) which declares ImageCropperModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

what should i do now ?

**Comment by lonerzzz** [comment]
Just an FYI, the issue (https://github.com/Mawi137/ngx-image-cropper/issues/353) is already tracking this problem.  Since it has not been addressed since August, it is likely to take more time until we see an issue.

**Comment by AliObaji** [comment]
Hey guys, I added this script ("postinstall": "ngcc") into my package.json as per this article https://www.xspdf.com/resolution/58743721.html.

Delete your node_modules and run a clean install. It worked for me.

**Comment by Mawi137** [comment]
The lib is built with Angular 8 which means it should be compatible with Angular 8 and up. Angular recommends to build libs with Ivy disabled to maintain compatibility for people that choose to keep using View Engine instead of Ivy. So you will indeed need to make sure that `ngcc` is run for this library (this even happens for the @angular/material library.

Working example with angular 10: https://stackblitz.com/edit/angular-ivy-vhb9m1

**Comment by JamesonNetworks** [comment]
For anyone that runs across this, I found that the issue was the path I was using to import. My auto complete on import tried to import:

ngx-image-cropper/lib/ngx-image-cropper.module

Changing to

ngx-image-cropper 

for the path to import resolved it.
