### ISSUE TITLE
Multiple imagecropper elements

### ISSUE THREAD

**Issue by shinbaka** [Mawi137/ngx-image-cropper#396]
Hello there,
On my application I have a editing page, that contain a foreach that will repeat with the users on my DB
and I've placed an imagecropper within each user, but when I upload one image, it uploads to the user that I've selected and then the loadImageFailed() message will appear for each imagecropper that I have on my page, how do I make each element have its own behavior?

I've used your own example to demonstrate 
https://stackblitz.com/edit/image-cropper-8myz86?file=app%2Fapp.component.html
when I upload one image, the functions from one cropper will work on the other too, I'm trying to leave each one with their own behavior.

Oh I've uploaded my example here, 
https://stackblitz.com/edit/image-cropper-hpbwtm?file=app/app.component.html
When I upload one image, for each image cropper that I have on my page, will trigger the load failed for the others.

**Comment by Mawi137** [comment]
Well you set the same `imageChangedEvent` to each cropper, but you only show one of the croppers so it will fail to load because they are not visible (but do exist).

The best approach would be to create a separate component with the file input field and code to open the image cropper modal. If you then use that component 3 times, they will all have their own context.

**Comment by danijel2017** [comment]
I have same issue. Currently I created a component image editor modal and it contains file input and other logic. And I created list with that component but when I change 2nd or later image it changed first one. How can I change correct item?
