### ISSUE TITLE
JPG format converted into PNG 

### ISSUE THREAD

**Issue by AR98** [Mawi137/ngx-image-cropper#456]
When I extract base64 from cropped image which is .jpg converted into .png ("base64":"data:image/png;base64) automatically. I need help to prevent it from converting png  and yes my image size also increases which is another issue for me, will love to see helping hand :-)

**Comment by JensSpanier** [comment]
Have a look at `format` in the [documentation](https://github.com/Mawi137/ngx-image-cropper#inputs).

**Comment by AR98** [comment]
> Have a look at `format` in the [documentation](https://github.com/Mawi137/ngx-image-cropper#inputs
Thanks but how to set **format** dynamic as user can upload different image formats png/jpg any idea?

**Comment by AR98** [comment]
@JensSpanier  Thanks but how to set **format** dynamic as user can upload different image formats png/jpg any idea?

**Comment by JensSpanier** [comment]
The image you select gets drawn to a canvas. At this point the image loses its original format.

By default it gets exported as png because all browsers support converting a canvas to png and png has no quality loss.

You could extract the file type when an image gets selected and use it as the input for `format`.

**Comment by AR98** [comment]
@JensSpanier  Thanks a lot man **:-) **
