### ISSUE TITLE
Uploaded file size is increasing dramatically

### ISSUE THREAD

**Issue by YSFKBDY** [Mawi137/ngx-image-cropper#539]
When I upload an image as a base64 string after with/without cropping it via cropper, the file's size is increasing dramatically. 

![image](https://user-images.githubusercontent.com/27686947/207548724-d026b479-99cd-4273-829e-5ade852196be.png)

![image](https://user-images.githubusercontent.com/27686947/207549042-e8c3c9f7-8f58-4425-97a0-da81e06672b8.png)

Right side is original file, left side is uploaded one. As far as I notice, this is happening with not 96 dpi or not 24 bit depth images. Cropper convert bit depth to 32 and dpi to 96.

**Comment by Mawi137** [comment]
Hi

The HTML canvas is used to crop the image. It's the native HTML canvas itself that gives these large base64 strings, so there's nothing I can do about that. Exporting as jpg instead of png helps, but you lose transparency. Else you'll have to look for another library that can compress the image.
