### ISSUE TITLE
event.base64 return undefined

### ISSUE THREAD

**Issue by duncanchiu409** [Mawi137/ngx-image-cropper#560]
I was following the example on the npm wiki page.

While implementation, I found the imageCropped isn't working.

the event is successfully prompted into method imageCropped, tho there is no base64 attribute and is undefined.

My setup: angular 13, Chrome, latest version ngx-image-cropper

**Comment by duncanchiu409** [comment]
I tried. version 6.3.4 which works. Can it be fixed???

**Comment by Mawi137** [comment]
The example was indeed incorrect due to some changes in v7.0.0. I updated the example in the readme here on github.

It will now emit a blob + objectUrl instead of a base64 string because consumes less memory and should keep the cropped images smaller. If you still want to get a base64 image, you'll have to add `output="base64"` in the HTML.

**Comment by duncanchiu409** [comment]
Thanks for the clarification. @Mawi137 Appreciate your work.
