### ISSUE TITLE
imageLoadedInView unable to be used for setting size, cropper, etc.

### ISSUE THREAD

**Issue by choskyo** [Mawi137/ngx-image-cropper#58]
Seems like a bug, following code prevents the imageLoaded event from being used to set the size or cropper values due to order of operations, will edit this if I find a solution.

component: 
```
imageLoadedInView(): void {
        if (this.originalImage != null) {
            this.imageLoaded.emit();
            setTimeout(() => {
                this.setMaxSize();
                this.resetCropperPosition();
                this.cd.markForCheck();
            });
        }
}
```

Following gives me expected functionality, unsure what purpose of setTimeout was here and had to call crop afterwards since it's private, could also just make that public.
```
    if (this.originalImage != null) {
      this.setMaxSize();
      this.resetCropperPosition();
      this.cd.markForCheck();
      this.imageLoaded.emit();
      this.crop();
    }
```

**Comment by Mawi137** [comment]
Hi, the problem is that it needs the cropper to be on the screen when the `imageLoadedInView` is called. So if you put a *ngIf on the cropper, it won't work, it doesn't work either when you use `display: none`. I only got it to work with `visibility: hidden`. Maybe I should let the cropper hide itself untill the image is loaded and I'll then add to the docs that you shouldn't use an ngIf or display: none
