### ISSUE TITLE
Exclusively support Angular 17 ?

### ISSUE THREAD

**Issue by PowerKiKi** [Mawi137/ngx-image-cropper#630]
Hi, would you accept a PR that migrate this project to:

- support exclusively Angular 17
- declare `ImageCropperComponent` as standalone
- drop entirely `ImageCropperModule` with no replacement
- migrate to new control flow syntax

If there is a chance to get it merged, then I'd create a PR for it. What do you think ?

**Comment by Mawi137** [comment]
Hi

- Standalone is supported since Angular 15 if I'm not mistaken. I would only upgrade to that version to keep the supported Angular versions aligned with the versions that the Angular team actively supports.
- The component can be converted to standalone, and the module dropped.
- Control flow syntax is still in developer preview I think, so I'd wait with that.

In that case I would accept the PR :)
