### ISSUE TITLE
Upgrade to 8.0.0

### ISSUE THREAD

**Issue by ilyakonrad** [Mawi137/ngx-image-cropper#634]
I'd like to know the breaking changes in v8, but there's no info in Releases.

![image](https://github.com/Mawi137/ngx-image-cropper/assets/25200186/2722062b-fb2c-4e1e-9208-cdc035ac0abc)

**Comment by zoltantoth89** [comment]
As I see the main (or only one?) breaking change is about the ImageCropperModule that should be replaced by the ImageCropperComponent, since it's became a standalone component. Seems like everything else works properly after that change. I found one warning message only on the console:

[NgxImageCropper] Could not find HammerJS - Pinch Gesture won't work

**Comment by GavynHolt** [comment]
I am getting warnings that it is actually not a standalone component as I make the adjustments. Looks like it must be brought in as a declaration, not an import. Is something amiss?

**Comment by Mawi137** [comment]
@ilyakonrad Sorry, forgot about that. I added the release. As @zoltantoth89 said, the component is indeed standalone now and the module was removed. You'll need at least Angular 16 for that.

@GavynHolt  The component has `standalone: true` which should be sufficient.

**Comment by kelvinsleonardo** [comment]
I'm facing the same issue.

**Comment by GavynHolt** [comment]
I must be off my rocker. Tried the adjustment today and all good. Thank you!
