### ISSUE TITLE
image cropped on click

### ISSUE THREAD

**Issue by rameezfsitix** [Mawi137/ngx-image-cropper#85]
Hi, how i can crop image on button click not drag the cropper. Thanks in advance

**Comment by vemuez** [comment]
I feel this may be something to think about since larger image files tend to slow down the applications by quite a bit as the cropper gets moved about and resized.

Use this image as an example:
http://www.effigis.com/wp-content/uploads/2015/02/DigitalGlobe_WorldView1_50cm_8bit_BW_DRA_Bangkok_Thailand_2009JAN06_8bits_sub_r_1.jpg

Here's the plunker:
https://embed.plnkr.co/fz0jtY/

**Comment by CreativeAcer** [comment]
To enable this i just added an input to trigger the crop on a button click and set autoTriggerCrop to false.
Added to image crop component 
 ``@Input()
    set triggerCrop(crop: Boolean) {
        if (crop) { this.crop(); }
    }``

and in the html you add in your page
[autoTriggerCrop]="false" [triggerCrop]="yourbuttonvar"
your button click will set yourbuttonvar to true which will trigger the cropping function

**Comment by Mawi137** [comment]
See comment in #92
